/*==============================================================================
             Customer Shopping Behavior Analysis
-------------------------------------------------------------------------------
   This script demonstrates how to analyze customer purchasing behavior
   using MySQL, covering revenue insights, product performance, and
   customer segmentation.

   Table of Contents:
     1. Basic Revenue Analysis
     2. Customer Spending Behavior
     3. Product Performance Analysis
     4. Shipping & Purchase Trends
     5. Subscription Insights
     6. Discount Analysis
     7. Customer Segmentation
     8. Category-wise Product Analysis
     9. Repeat Buyer Insights
     10. Demographic Revenue Analysis
==============================================================================*/

/*------------------------------------------------------------------------------
1. BASIC REVENUE ANALYSIS
------------------------------------------------------------------------------*/

-- Q1. What is the total revenue generated by male vs. female customers?
      SELECT 
         gender,
         SUM(purchase_amount) AS revenue
	 FROM customer
     GROUP BY gender;
     
 -- Insight: Male customers contribute nearly twice the revenue of female customers, making them the primary revenue drivers.
 
 /*------------------------------------------------------------------------------
2. CUSTOMER SPENDING BEHAVIOR
------------------------------------------------------------------------------*/

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

-- Using Subquery 
SELECT 
     customer_id,
     discount_applied,
     purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) AS avg_purchase_amount FROM customer);

-- Using Subquery & Window Function 
SELECT
*
FROM(
		SELECT 
			 customer_id,
			 discount_applied,
			 purchase_amount,
			 Round(AVG(purchase_amount) Over(),2) AS avg_purchase_amount
		FROM customer
)t 
WHERE discount_applied = 'Yes' AND purchase_amount >= avg_purchase_amount;

-- Insight: A limited segment (839 customers) continues to spend above average even with discounts, highlighting a niche group with strong purchase intent and high value.

/*------------------------------------------------------------------------------
3. PRODUCT PERFORMANCE ANALYSIS
------------------------------------------------------------------------------*/

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, 
       ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Insight: Top-rated products show minimal variation (~3.78–3.86), suggesting overall consistent product quality rather than a single standout item.

/*------------------------------------------------------------------------------
4. SHIPPING & PURCHASE TRENDS
------------------------------------------------------------------------------*/

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT 
    shipping_type,
    ROUND(Avg(purchase_amount),2) AS avg_purchase_amt
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Insight: Customers using Express shipping have a slightly higher average purchase (~60.48) than Standard (~58.46), indicating a tendency to spend more for faster delivery.

/*------------------------------------------------------------------------------
5. SUBSCRIPTION INSIGHTS
------------------------------------------------------------------------------*/

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
    
SELECT 
	subscription_status,
	ROUND(AVG(purchase_amount),2) AS avg_Spent,
    SUM(Purchase_amount) AS revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spent, revenue;

-- Insight: Non-subscribers generate significantly higher total revenue (170,436) than subscribers (62,645), despite having a similar average spend per purchase.

/*------------------------------------------------------------------------------
6. DISCOUNT ANALYSIS
------------------------------------------------------------------------------*/

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
   item_purchased,
   ROUND(
       SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
       /COUNT(*) * 100,
	2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Insight: Hats, Sneakers, and Coats have the highest discount usage (~47–50%), indicating these products are more dependent on promotions to drive sales.

/*------------------------------------------------------------------------------
7. CUSTOMER SEGMENTATION
------------------------------------------------------------------------------*/

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
       
-- CTE query
WITH customer_type AS
(
SELECT 
   customer_id,
  previous_purchases,
   CASE 
	   WHEN previous_purchases = 1 THEN 'New'
	   WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	   ELSE 'Loyal'
   END AS customer_segment
FROM customer
)
-- Main Query
SELECT 
    customer_segment,
    COUNT(*) AS  ' Number of customers'
FROM customer_type
GROUP BY customer_segment;

-- Insight: The majority of customers are Loyal (3116), indicating a highly retained customer base, while New customers (83) are very low, suggesting weak customer acquisition.

/*------------------------------------------------------------------------------
8. CATEGORY-WISE PRODUCT ANALYSIS
------------------------------------------------------------------------------*/

-- Q8. What are the top 3 most purchased products within each category? 

 WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
   item_rank,
   category, 
   item_purchased, 
   total_orders
FROM item_counts
WHERE item_rank <=3;

-- Insight: Top products across categories show very similar order volumes, suggesting evenly distributed customer preferences rather than a single dominant product.

/*------------------------------------------------------------------------------
9. REPEAT BUYER INSIGHTS
------------------------------------------------------------------------------*/

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Insight: Most repeat buyers are non-subscribers (2518 vs 958), indicating that repeat purchases are not strongly driven by subscription.

/*------------------------------------------------------------------------------
10. DEMOGRAPHIC REVENUE ANALYSIS
------------------------------------------------------------------------------*/

-- Q10. What is the revenue contribution of each age group? 

SELECT 
   age_group,
   SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Insight: Young Adults generate the highest revenue (62,143), but overall revenue is fairly evenly distributed across all age groups.